"use client";

import { useState, useCallback, useRef, useEffect } from "react";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import {
  updateSponsorProfile,
  checkSponsorSlugAvailability,
  updateSponsorLogo,
  removeSponsorLogo,
} from "@/app/(sponsor)/sponsor/(dashboard)/settings/actions";
import { LogoCropModal } from "@/components/sponsor/logo-crop-modal";
import { createClient } from "@/lib/supabase/client";
import { toast } from "sonner";
import { Check, X, Loader2, Upload, Crop, Trash2, Building2, Users } from "lucide-react";
import { TimezonePicker } from "@fanflet/ui/timezone-picker";
import { TIMEZONE_OPTIONS, getBrowserTimezone } from "@fanflet/db/timezone";

const ACCEPTED_IMAGE_TYPES = ["image/jpeg", "image/png", "image/webp", "image/gif", "image/svg+xml"];
const MAX_LOGO_SIZE = 2 * 1024 * 1024;

function slugify(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

interface SponsorSettingsFormProps {
  sponsor: {
    id: string;
    company_name: string;
    slug: string | null;
    description: string | null;
    logo_url: string | null;
    website_url: string | null;
    contact_email: string;
    industry: string | null;
    timezone: string | null;
  };
  authUserId: string;
  userEmail: string;
}

export function SponsorSettingsForm({ sponsor, authUserId, userEmail }: SponsorSettingsFormProps) {
  const [companyName, setCompanyName] = useState(sponsor.company_name);
  const [slug, setSlug] = useState(sponsor.slug ?? "");
  const [description, setDescription] = useState(sponsor.description ?? "");
  const [contactEmail, setContactEmail] = useState(sponsor.contact_email ?? userEmail);
  const [websiteUrl, setWebsiteUrl] = useState(sponsor.website_url ?? "");
  const [industry, setIndustry] = useState(sponsor.industry ?? "");
  const [logoUrl, setLogoUrl] = useState(sponsor.logo_url ?? "");
  const [timezone, setTimezone] = useState(sponsor.timezone ?? getBrowserTimezone());

  const [slugAvailable, setSlugAvailable] = useState<boolean | null>(null);
  const [slugChecking, setSlugChecking] = useState(false);
  const [saving, setSaving] = useState(false);
  const [hasAutoGeneratedSlug, setHasAutoGeneratedSlug] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [removingLogo, setRemovingLogo] = useState(false);
  const [cropModalOpen, setCropModalOpen] = useState(false);
  const [cropModalFile, setCropModalFile] = useState<File | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const slugCheckTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    if (!hasAutoGeneratedSlug && companyName && (!slug || !sponsor.slug)) {
      const generated = slugify(companyName);
      if (generated) {
        queueMicrotask(() => {
          setSlug(generated);
          setHasAutoGeneratedSlug(true);
        });
      }
    }
  }, [companyName, hasAutoGeneratedSlug, slug, sponsor.slug]);

  const checkSlug = useCallback(async (value: string) => {
    if (!value.trim()) {
      setSlugAvailable(null);
      return;
    }
    if (!/^[a-z0-9-]+$/.test(value)) {
      setSlugAvailable(false);
      return;
    }
    setSlugChecking(true);
    const result = await checkSponsorSlugAvailability(value);
    setSlugAvailable(result.available);
    setSlugChecking(false);
  }, []);

  useEffect(() => {
    if (slugCheckTimeoutRef.current) {
      clearTimeout(slugCheckTimeoutRef.current);
    }
    if (!slug.trim()) {
      queueMicrotask(() => setSlugAvailable(null));
      return;
    }
    slugCheckTimeoutRef.current = setTimeout(() => {
      checkSlug(slug);
    }, 300);
    return () => {
      if (slugCheckTimeoutRef.current) {
        clearTimeout(slugCheckTimeoutRef.current);
      }
    };
  }, [slug, checkSlug]);

  const handleLogoSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!ACCEPTED_IMAGE_TYPES.includes(file.type)) {
      toast.error("Please select a JPEG, PNG, WebP, GIF, or SVG image.");
      return;
    }
    if (file.size > MAX_LOGO_SIZE) {
      toast.error("Logo must be under 2 MB.");
      return;
    }

    setCropModalFile(file);
    setCropModalOpen(true);
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  const handleCropSaved = useCallback(
    async (croppedBlob: Blob) => {
      setUploading(true);
      try {
        const supabase = createClient();
        const path = `${authUserId}/sponsor-logo-${Date.now()}.png`;

        const { error: uploadError } = await supabase.storage
          .from("avatars")
          .upload(path, croppedBlob, { upsert: true, contentType: "image/png" });

        if (uploadError) {
          toast.error(uploadError.message || "Logo upload failed.");
          return;
        }

        const { data } = supabase.storage.from("avatars").getPublicUrl(path);
        const result = await updateSponsorLogo(data.publicUrl);
        if (result.error) {
          toast.error(result.error);
          return;
        }
        setLogoUrl(data.publicUrl);
        toast.success("Logo updated.");
      } finally {
        setUploading(false);
        setCropModalFile(null);
      }
    },
    [authUserId]
  );

  const handleCropOpenChange = useCallback((open: boolean) => {
    setCropModalOpen(open);
    if (!open) setCropModalFile(null);
  }, []);

  const handleRemoveLogo = useCallback(async () => {
    if (!logoUrl) return;
    setRemovingLogo(true);
    const result = await removeSponsorLogo();
    if (result.error) {
      toast.error(result.error);
      setRemovingLogo(false);
      return;
    }
    setLogoUrl("");
    toast.success("Logo removed.");
    setRemovingLogo(false);
  }, [logoUrl]);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!companyName.trim()) {
      toast.error("Company name is required.");
      return;
    }
    if (!contactEmail.trim()) {
      toast.error("Contact email is required.");
      return;
    }
    if (slugAvailable === false) {
      toast.error("Please choose an available URL slug.");
      return;
    }

    setSaving(true);
    const formData = new FormData();
    formData.set("company_name", companyName.trim());
    formData.set("slug", slug.trim());
    formData.set("description", description.trim());
    formData.set("contact_email", contactEmail.trim());
    formData.set("website_url", websiteUrl.trim());
    formData.set("industry", industry.trim());
    formData.set("timezone", timezone);

    const result = await updateSponsorProfile(formData);

    if (result.error) {
      toast.error(result.error);
      setSaving(false);
      return;
    }

    toast.success("Company profile saved.");
    setSaving(false);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-8 max-w-2xl">
      {/* Company Logo */}
      <Card className="border-[#e2e8f0]">
        <CardHeader>
          <CardTitle className="text-zinc-900">Company Logo</CardTitle>
          <CardDescription>
            Your logo appears to speakers reviewing connection requests. Square crop recommended.
            JPEG, PNG, WebP, GIF, or SVG under 2 MB.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col sm:flex-row items-start gap-6">
          <div className="w-20 h-20 rounded-lg border-2 border-[#e2e8f0] bg-gray-50 flex items-center justify-center overflow-hidden shrink-0">
            {logoUrl ? (
              <Image
                src={logoUrl}
                alt="Company logo"
                width={80}
                height={80}
                className="w-full h-full object-contain"
                unoptimized
              />
            ) : (
              <Building2 className="w-8 h-8 text-gray-300" />
            )}
          </div>
          <div className="flex flex-col gap-2">
            <input
              ref={fileInputRef}
              type="file"
              accept="image/jpeg,image/png,image/webp,image/gif,image/svg+xml"
              className="hidden"
              onChange={handleLogoSelect}
              disabled={uploading || cropModalOpen}
            />
            <Button
              type="button"
              variant="outline"
              onClick={() => fileInputRef.current?.click()}
              disabled={uploading || cropModalOpen}
              className="border-teal-500 text-zinc-900 hover:bg-teal-50"
            >
              {uploading ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <Upload className="w-4 h-4" />
              )}
              {uploading ? "Uploading..." : "Upload Logo"}
            </Button>
            {logoUrl && (
              <>
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => fileInputRef.current?.click()}
                  disabled={uploading || cropModalOpen}
                  className="border-[#e2e8f0] text-zinc-900 hover:bg-gray-100"
                >
                  <Crop className="w-4 h-4" />
                  Replace &amp; crop
                </Button>
                <Button
                  type="button"
                  variant="ghost"
                  onClick={handleRemoveLogo}
                  disabled={removingLogo || cropModalOpen}
                  className="text-destructive hover:text-destructive hover:bg-destructive/10"
                >
                  {removingLogo ? (
                    <Loader2 className="w-4 h-4 animate-spin" />
                  ) : (
                    <Trash2 className="w-4 h-4" />
                  )}
                  Remove logo
                </Button>
              </>
            )}
            <LogoCropModal
              open={cropModalOpen}
              onOpenChange={handleCropOpenChange}
              file={cropModalFile}
              onSaved={handleCropSaved}
            />
          </div>
        </CardContent>
      </Card>

      {/* Company Profile */}
      <Card className="border-[#e2e8f0]">
        <CardHeader>
          <CardTitle className="text-zinc-900">Company Profile</CardTitle>
          <CardDescription>
            Basic details about your company. Speakers see this when reviewing connection requests.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="company_name" className="text-zinc-900">
              Company name <span className="text-destructive">*</span>
            </Label>
            <Input
              id="company_name"
              value={companyName}
              onChange={(e) => setCompanyName(e.target.value)}
              placeholder="Acme Inc."
              required
              className="border-[#e2e8f0] focus:border-teal-500 focus:ring-teal-500/30"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="slug" className="text-zinc-900">
              URL slug
            </Label>
            <div className="flex items-center gap-2">
              <div className="flex-1 flex items-center gap-2">
                <Input
                  id="slug"
                  value={slug}
                  onChange={(e) =>
                    setSlug(
                      e.target.value
                        .toLowerCase()
                        .replace(/\s+/g, "-")
                        .replace(/[^a-z0-9-]/g, "")
                    )
                  }
                  placeholder="acme-inc"
                  className="border-[#e2e8f0] focus:border-teal-500 focus:ring-teal-500/30 font-mono"
                />
                {slugChecking && (
                  <Loader2 className="w-4 h-4 animate-spin text-muted-foreground shrink-0" />
                )}
                {!slugChecking && slug.trim() && slugAvailable === true && (
                  <Check className="w-5 h-5 text-emerald-600 shrink-0" />
                )}
                {!slugChecking && slug.trim() && slugAvailable === false && (
                  <X className="w-5 h-5 text-destructive shrink-0" />
                )}
              </div>
            </div>
            <p className="text-xs text-muted-foreground">
              Lowercase letters, numbers, and hyphens only. Used for shareable links.
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="description" className="text-zinc-900">
              Company description
            </Label>
            <Textarea
              id="description"
              value={description}
              onChange={(e) => setDescription(e.target.value.slice(0, 500))}
              placeholder="Tell speakers about your company and what you offer..."
              maxLength={500}
              rows={4}
              className="border-[#e2e8f0] focus:border-teal-500 focus:ring-teal-500/30 resize-none"
            />
            <p className="text-xs text-muted-foreground text-right">
              {description.length}/500
            </p>
          </div>
        </CardContent>
      </Card>

      {/* Contact & Links */}
      <Card className="border-[#e2e8f0]">
        <CardHeader>
          <CardTitle className="text-zinc-900">Contact &amp; Links</CardTitle>
          <CardDescription>
            How speakers and the Fanflet team can reach you.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="contact_email" className="text-zinc-900">
              Contact email <span className="text-destructive">*</span>
            </Label>
            <Input
              id="contact_email"
              type="email"
              value={contactEmail}
              onChange={(e) => setContactEmail(e.target.value)}
              placeholder="partnerships@company.com"
              required
              className="border-[#e2e8f0] focus:border-teal-500 focus:ring-teal-500/30"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="website_url" className="text-zinc-900">
              Website
            </Label>
            <Input
              id="website_url"
              type="url"
              value={websiteUrl}
              onChange={(e) => setWebsiteUrl(e.target.value)}
              placeholder="https://www.company.com"
              className="border-[#e2e8f0] focus:border-teal-500 focus:ring-teal-500/30"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="industry" className="text-zinc-900">
              Industry
            </Label>
            <Input
              id="industry"
              value={industry}
              onChange={(e) => setIndustry(e.target.value)}
              placeholder="e.g. Dental supplies, Medical devices"
              className="border-[#e2e8f0] focus:border-teal-500 focus:ring-teal-500/30"
            />
          </div>
        </CardContent>
      </Card>

      {/* Timezone */}
      <Card className="border-[#e2e8f0]">
        <CardHeader>
          <CardTitle className="text-zinc-900">Timezone</CardTitle>
          <CardDescription>
            Dates and times in your dashboard are displayed in this timezone.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <TimezonePicker
            value={timezone}
            onValueChange={setTimezone}
            options={TIMEZONE_OPTIONS}
            className="w-full max-w-sm border-[#e2e8f0] focus:border-teal-500 focus:ring-teal-500/30"
          />
        </CardContent>
      </Card>

      {/* Authorized Users - Coming Soon */}
      <Card className="border-[#e2e8f0] opacity-60">
        <CardHeader>
          <div className="flex items-center gap-3">
            <CardTitle className="text-zinc-900">Authorized Users</CardTitle>
            <span className="inline-flex items-center rounded-full bg-gray-100 px-2.5 py-0.5 text-xs font-medium text-gray-500">
              Coming soon
            </span>
          </div>
          <CardDescription>
            Invite team members to manage your sponsor account on Fanflet. Control who can view leads, manage connections, and update your company profile.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="flex items-center gap-3 text-gray-400">
            <Users className="w-5 h-5" />
            <p className="text-sm">Team management will be available in a future update.</p>
          </div>
        </CardContent>
      </Card>

      <Button
        type="submit"
        disabled={saving || slugAvailable === false}
        className="bg-zinc-900 hover:bg-zinc-800 text-white px-8"
      >
        {saving ? (
          <>
            <Loader2 className="w-4 h-4 animate-spin" />
            Saving...
          </>
        ) : (
          "Save Changes"
        )}
      </Button>
    </form>
  );
}
