"use client";

import { useState, useCallback, useRef, useEffect } from "react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { createClient } from "@/lib/supabase/client";
import {
  updateSpeakerProfile,
  checkSlugAvailability,
  updateSpeakerPhoto,
} from "@/app/dashboard/settings/actions";
import { toast } from "sonner";
import { Check, X, Loader2, Upload } from "lucide-react";

type SpeakerProfile = {
  id: string;
  name: string | null;
  bio: string | null;
  photo_url: string | null;
  slug: string | null;
  social_links: { linkedin?: string; twitter?: string; website?: string } | null;
};

function slugify(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

function getInitials(name: string | null, email: string): string {
  if (name && name.trim()) {
    const parts = name.trim().split(/\s+/);
    if (parts.length >= 2) {
      return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase().slice(0, 2);
    }
    return name.slice(0, 2).toUpperCase();
  }
  if (email) {
    return email.slice(0, 2).toUpperCase();
  }
  return "??";
}

interface SettingsFormProps {
  speaker: SpeakerProfile | null;
  authUserId: string;
  userEmail: string;
}

export function SettingsForm({ speaker, authUserId, userEmail }: SettingsFormProps) {
  const [name, setName] = useState(speaker?.name ?? "");
  const [bio, setBio] = useState(speaker?.bio ?? "");
  const [slug, setSlug] = useState(speaker?.slug ?? "");
  const [photoUrl, setPhotoUrl] = useState(speaker?.photo_url ?? "");
  const [linkedin, setLinkedin] = useState(speaker?.social_links?.linkedin ?? "");
  const [twitter, setTwitter] = useState(speaker?.social_links?.twitter ?? "");
  const [website, setWebsite] = useState(speaker?.social_links?.website ?? "");

  const [slugAvailable, setSlugAvailable] = useState<boolean | null>(null);
  const [slugChecking, setSlugChecking] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [hasAutoGeneratedSlug, setHasAutoGeneratedSlug] = useState(false);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const slugCheckTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Auto-generate slug from name on first visit (when slug is empty)
  useEffect(() => {
    if (!hasAutoGeneratedSlug && name && (!slug || !speaker?.slug)) {
      const generated = slugify(name);
      if (generated) {
        queueMicrotask(() => {
          setSlug(generated);
          setHasAutoGeneratedSlug(true);
        });
      }
    }
  }, [name, hasAutoGeneratedSlug, slug, speaker?.slug]);

  // Debounced slug availability check
  const checkSlug = useCallback(async (value: string) => {
    if (!value.trim()) {
      setSlugAvailable(null);
      return;
    }
    const validSlug = /^[a-z0-9-]+$/.test(value);
    if (!validSlug) {
      setSlugAvailable(false);
      return;
    }
    setSlugChecking(true);
    const result = await checkSlugAvailability(value);
    setSlugAvailable(result.available);
    setSlugChecking(false);
  }, []);

  useEffect(() => {
    if (slugCheckTimeoutRef.current) {
      clearTimeout(slugCheckTimeoutRef.current);
    }
    if (!slug.trim()) {
      queueMicrotask(() => setSlugAvailable(null));
      return;
    }
    slugCheckTimeoutRef.current = setTimeout(() => {
      checkSlug(slug);
    }, 300);
    return () => {
      if (slugCheckTimeoutRef.current) {
        clearTimeout(slugCheckTimeoutRef.current);
      }
    };
  }, [slug, checkSlug]);

  const handlePhotoSelect = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file || !authUserId) return;

    const validTypes = ["image/jpeg", "image/png", "image/webp", "image/gif"];
    if (!validTypes.includes(file.type)) {
      toast.error("Please select a JPEG, PNG, WebP, or GIF image.");
      return;
    }
    if (file.size > 5 * 1024 * 1024) {
      toast.error("Image must be under 5MB.");
      return;
    }

    setUploading(true);
    const supabase = createClient();
    const ext = file.name.split(".").pop() || "jpg";
    const path = `${authUserId}/${Date.now()}.${ext}`;

    const { error } = await supabase.storage.from("avatars").upload(path, file, {
      upsert: true,
    });

    if (error) {
      toast.error(error.message || "Upload failed.");
      setUploading(false);
      return;
    }

    const { data } = supabase.storage.from("avatars").getPublicUrl(path);
    const publicUrl = data.publicUrl;

    const result = await updateSpeakerPhoto(publicUrl);
    if (result.error) {
      toast.error(result.error);
      setUploading(false);
      return;
    }

    setPhotoUrl(publicUrl);
    toast.success("Photo updated.");
    setUploading(false);
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!name.trim()) {
      toast.error("Name is required.");
      return;
    }
    if (!slug.trim()) {
      toast.error("Speaker URL slug is required.");
      return;
    }
    if (slugAvailable === false) {
      toast.error("Please choose an available URL slug.");
      return;
    }

    setSaving(true);
    const formData = new FormData();
    formData.set("name", name.trim());
    formData.set("bio", bio);
    formData.set("slug", slug.trim());
    if (photoUrl) formData.set("photo_url", photoUrl);
    formData.set("linkedin", linkedin.trim());
    formData.set("twitter", twitter.trim());
    formData.set("website", website.trim());

    const result = await updateSpeakerProfile(formData);

    if (result.error) {
      toast.error(result.error);
      setSaving(false);
      return;
    }

    toast.success("Profile saved successfully.");
    setSaving(false);
  };

  const displayPhotoUrl = photoUrl || undefined;
  const initials = getInitials(name || speaker?.name || null, userEmail);

  return (
    <form onSubmit={handleSubmit} className="space-y-8 max-w-2xl">
      {/* Photo upload section */}
      <Card className="border-[#e2e8f0]">
        <CardHeader>
          <CardTitle className="text-[#1B365D]">Profile Photo</CardTitle>
          <CardDescription>
            Your photo appears on your Fanflet pages. JPG, PNG, or WebP under 5MB.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col sm:flex-row items-start gap-6">
          <Avatar className="w-20 h-20 border-2 border-[#e2e8f0] shrink-0">
            <AvatarImage src={displayPhotoUrl} alt="Profile" className="object-cover" />
            <AvatarFallback className="bg-[#3BA5D9]/20 text-[#1B365D] text-xl font-semibold">
              {initials}
            </AvatarFallback>
          </Avatar>
          <div className="flex flex-col gap-2">
            <input
              ref={fileInputRef}
              type="file"
              accept="image/jpeg,image/png,image/webp,image/gif"
              className="hidden"
              onChange={handlePhotoSelect}
              disabled={uploading}
            />
            <Button
              type="button"
              variant="outline"
              onClick={() => fileInputRef.current?.click()}
              disabled={uploading}
              className="border-[#3BA5D9] text-[#1B365D] hover:bg-[#3BA5D9]/10"
            >
              {uploading ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Uploading...
                </>
              ) : (
                <>
                  <Upload className="w-4 h-4" />
                  Upload Photo
                </>
              )}
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Profile fields */}
      <Card className="border-[#e2e8f0]">
        <CardHeader>
          <CardTitle className="text-[#1B365D]">Profile Information</CardTitle>
          <CardDescription>
            Basic details that appear on your public Fanflet pages.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="name" className="text-[#1B365D]">
              Name <span className="text-destructive">*</span>
            </Label>
            <Input
              id="name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="Your full name"
              required
              className="border-[#e2e8f0] focus:border-[#3BA5D9] focus:ring-[#3BA5D9]/30"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="bio" className="text-[#1B365D]">
              Bio
            </Label>
            <Textarea
              id="bio"
              value={bio}
              onChange={(e) => setBio(e.target.value.slice(0, 500))}
              placeholder="A short bio about you..."
              maxLength={500}
              rows={4}
              className="border-[#e2e8f0] focus:border-[#3BA5D9] focus:ring-[#3BA5D9]/30 resize-none"
            />
            <p className="text-xs text-muted-foreground text-right">
              {bio.length}/500
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="slug" className="text-[#1B365D]">
              Speaker URL <span className="text-destructive">*</span>
            </Label>
            <div className="flex items-center gap-2">
              <span className="text-sm text-muted-foreground whitespace-nowrap shrink-0">
                fanflet.com/
              </span>
              <div className="flex-1 flex items-center gap-2">
                <Input
                  id="slug"
                  value={slug}
                  onChange={(e) =>
                    setSlug(
                      e.target.value
                        .toLowerCase()
                        .replace(/\s+/g, "-")
                        .replace(/[^a-z0-9-]/g, "")
                    )
                  }
                  placeholder="your-name"
                  required
                  className="border-[#e2e8f0] focus:border-[#3BA5D9] focus:ring-[#3BA5D9]/30 font-mono"
                />
                {slugChecking && (
                  <Loader2 className="w-4 h-4 animate-spin text-muted-foreground shrink-0" />
                )}
                {!slugChecking && slug.trim() && slugAvailable === true && (
                  <Check className="w-5 h-5 text-emerald-600 shrink-0" />
                )}
                {!slugChecking && slug.trim() && slugAvailable === false && (
                  <X className="w-5 h-5 text-destructive shrink-0" />
                )}
              </div>
            </div>
            <p className="text-xs text-muted-foreground">
              Lowercase letters, numbers, and hyphens only. Your page will be at
              fanflet.com/{slug || "your-slug"}.
            </p>
          </div>
        </CardContent>
      </Card>

      {/* Social links */}
      <Card className="border-[#e2e8f0]">
        <CardHeader>
          <CardTitle className="text-[#1B365D]">Social Links</CardTitle>
          <CardDescription>
            Optional links to display on your Fanflet pages.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="linkedin" className="text-[#1B365D]">
              LinkedIn
            </Label>
            <Input
              id="linkedin"
              type="url"
              value={linkedin}
              onChange={(e) => setLinkedin(e.target.value)}
              placeholder="https://linkedin.com/in/yourprofile"
              className="border-[#e2e8f0] focus:border-[#3BA5D9] focus:ring-[#3BA5D9]/30"
            />
          </div>
          <Separator />
          <div className="space-y-2">
            <Label htmlFor="twitter" className="text-[#1B365D]">
              X (Twitter)
            </Label>
            <Input
              id="twitter"
              type="url"
              value={twitter}
              onChange={(e) => setTwitter(e.target.value)}
              placeholder="https://x.com/yourhandle"
              className="border-[#e2e8f0] focus:border-[#3BA5D9] focus:ring-[#3BA5D9]/30"
            />
          </div>
          <Separator />
          <div className="space-y-2">
            <Label htmlFor="website" className="text-[#1B365D]">
              Website
            </Label>
            <Input
              id="website"
              type="url"
              value={website}
              onChange={(e) => setWebsite(e.target.value)}
              placeholder="https://yoursite.com"
              className="border-[#e2e8f0] focus:border-[#3BA5D9] focus:ring-[#3BA5D9]/30"
            />
          </div>
        </CardContent>
      </Card>

      <Button
        type="submit"
        disabled={saving || slugAvailable === false}
        className="bg-[#1B365D] hover:bg-[#1B365D]/90 text-white px-8"
      >
        {saving ? (
          <>
            <Loader2 className="w-4 h-4 animate-spin" />
            Saving...
          </>
        ) : (
          "Save Profile"
        )}
      </Button>
    </form>
  );
}
