"use client";

import { useState, useCallback, useRef, useEffect } from "react";
import { useSearchParams } from "next/navigation";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import {
  updateSpeakerProfile,
  checkSlugAvailability,
} from "@/app/dashboard/settings/actions";
import { PhotoCropModal } from "@/components/dashboard/photo-crop-modal";
import { ThemePicker } from "@/components/fanflet-builder/theme-picker";
import { getPhotoFrameImageStyle, readPhotoFrame, type PhotoFrame } from "@/lib/photo-frame";
import { getDefaultThemePreset } from "@/lib/speaker-preferences";
import { toast } from "sonner";
import { Check, X, Loader2, Upload, Trash2 } from "lucide-react";

type SpeakerProfile = {
  id: string;
  name: string | null;
  bio: string | null;
  photo_url: string | null;
  slug: string | null;
  social_links: {
    linkedin?: string;
    twitter?: string;
    website?: string;
    photo_frame?: PhotoFrame;
    default_theme_preset?: string;
  } | null;
};

function slugify(text: string): string {
  return text
    .toLowerCase()
    .trim()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

function getInitials(name: string | null, email: string): string {
  if (name && name.trim()) {
    const parts = name.trim().split(/\s+/);
    if (parts.length >= 2) {
      return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase().slice(0, 2);
    }
    return name.slice(0, 2).toUpperCase();
  }
  if (email) {
    return email.slice(0, 2).toUpperCase();
  }
  return "??";
}

interface SettingsFormProps {
  speaker: SpeakerProfile | null;
  authUserId: string;
  userEmail: string;
  /** When false, only the base theme is selectable in ThemePicker (free tier). */
  allowMultipleThemes?: boolean;
}

export function SettingsForm({ speaker, authUserId, userEmail, allowMultipleThemes = true }: SettingsFormProps) {
  const searchParams = useSearchParams();
  const [name, setName] = useState(speaker?.name ?? "");
  const [bio, setBio] = useState(speaker?.bio ?? "");
  const [slug, setSlug] = useState(speaker?.slug ?? "");
  const [photoUrl, setPhotoUrl] = useState(speaker?.photo_url ?? "");
  const [photoFrame, setPhotoFrame] = useState<PhotoFrame | null>(readPhotoFrame(speaker?.social_links ?? null));
  const [linkedin, setLinkedin] = useState(speaker?.social_links?.linkedin ?? "");
  const [twitter, setTwitter] = useState(speaker?.social_links?.twitter ?? "");
  const [website, setWebsite] = useState(speaker?.social_links?.website ?? "");
  const [defaultThemePreset, setDefaultThemePreset] = useState(getDefaultThemePreset(speaker?.social_links ?? null));

  const [slugAvailable, setSlugAvailable] = useState<boolean | null>(null);
  const [slugChecking, setSlugChecking] = useState(false);
  const [saving, setSaving] = useState(false);
  const [hasAutoGeneratedSlug, setHasAutoGeneratedSlug] = useState(false);
  const [removePhoto, setRemovePhoto] = useState(false);
  const [cropModalOpen, setCropModalOpen] = useState(false);
  const [cropModalFile, setCropModalFile] = useState<File | null>(null);
  const [cropModalExistingUrl, setCropModalExistingUrl] = useState<string | null>(null);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const slugCheckTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Auto-generate slug from name on first visit (when slug is empty)
  useEffect(() => {
    if (!hasAutoGeneratedSlug && name && (!slug || !speaker?.slug)) {
      const generated = slugify(name);
      if (generated) {
        queueMicrotask(() => {
          setSlug(generated);
          setHasAutoGeneratedSlug(true);
        });
      }
    }
  }, [name, hasAutoGeneratedSlug, slug, speaker?.slug]);

  // Debounced slug availability check
  const checkSlug = useCallback(async (value: string) => {
    if (!value.trim()) {
      setSlugAvailable(null);
      return;
    }
    const validSlug = /^[a-z0-9-]+$/.test(value);
    if (!validSlug) {
      setSlugAvailable(false);
      return;
    }
    setSlugChecking(true);
    const result = await checkSlugAvailability(value);
    setSlugAvailable(result.available);
    setSlugChecking(false);
  }, []);

  useEffect(() => {
    if (slugCheckTimeoutRef.current) {
      clearTimeout(slugCheckTimeoutRef.current);
    }
    if (!slug.trim()) {
      queueMicrotask(() => setSlugAvailable(null));
      return;
    }
    slugCheckTimeoutRef.current = setTimeout(() => {
      checkSlug(slug);
    }, 300);
    return () => {
      if (slugCheckTimeoutRef.current) {
        clearTimeout(slugCheckTimeoutRef.current);
      }
    };
  }, [slug, checkSlug]);

  useEffect(() => {
    const focusTarget = searchParams.get("focus");
    if (!focusTarget) return;

    const scrollToId = (id: string) => {
      const section = document.getElementById(id);
      section?.scrollIntoView({ behavior: "smooth", block: "start" });
      return section;
    };

    const run = () => {
      if (focusTarget === "photo") {
        scrollToId("profile-photo-section");
        (document.getElementById("upload-photo-button") as HTMLButtonElement | null)?.focus();
        return;
      }

      if (focusTarget === "name") {
        scrollToId("profile-info-section");
        const input = document.getElementById("name") as HTMLInputElement | null;
        input?.focus();
        input?.select();
        return;
      }

      if (focusTarget === "public-link") {
        scrollToId("profile-info-section");
        const input = document.getElementById("slug") as HTMLInputElement | null;
        input?.focus();
        input?.select();
        return;
      }

      if (focusTarget === "default-theme") {
        const section = scrollToId("default-theme-section");
        (section?.querySelector("button") as HTMLButtonElement | null)?.focus();
      }
    };

    const timeoutId = window.setTimeout(run, 50);
    return () => window.clearTimeout(timeoutId);
  }, [searchParams]);

  const handlePhotoSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file || !authUserId) return;

    const validTypes = ["image/jpeg", "image/png", "image/webp", "image/gif"];
    if (!validTypes.includes(file.type)) {
      toast.error("Please select a JPEG, PNG, WebP, or GIF image.");
      return;
    }
    if (file.size > 5 * 1024 * 1024) {
      toast.error("Image must be under 5MB.");
      return;
    }

    setCropModalFile(file);
    setCropModalOpen(true);
    if (fileInputRef.current) fileInputRef.current.value = "";
  };

  const handleCropSaved = useCallback((url: string, frame: PhotoFrame) => {
    setPhotoUrl(url);
    setPhotoFrame(frame);
    setRemovePhoto(false);
    setCropModalFile(null);
  }, []);

  const handleCropOpenChange = useCallback((open: boolean) => {
    setCropModalOpen(open);
    if (!open) {
      setCropModalFile(null);
      setCropModalExistingUrl(null);
    }
  }, []);

  const handleAdjustPhoto = useCallback(() => {
    if (!photoUrl) return;
    setCropModalExistingUrl(photoUrl);
    setCropModalFile(null);
    setCropModalOpen(true);
  }, [photoUrl]);

  const handleRemovePhoto = useCallback(() => {
    setPhotoUrl("");
    setPhotoFrame(null);
    setRemovePhoto(true);
  }, []);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    if (!name.trim()) {
      toast.error("Name is required.");
      return;
    }
    if (!slug.trim()) {
      toast.error("Public profile link is required.");
      return;
    }
    if (slugAvailable === false) {
      toast.error("Please choose an available public profile link.");
      return;
    }

    setSaving(true);
    const formData = new FormData();
    formData.set("name", name.trim());
    formData.set("bio", bio);
    formData.set("slug", slug.trim());
    if (photoUrl) formData.set("photo_url", photoUrl);
    if (removePhoto) formData.set("remove_photo", "true");
    formData.set("linkedin", linkedin.trim());
    formData.set("twitter", twitter.trim());
    formData.set("website", website.trim());
    formData.set("default_theme_preset", defaultThemePreset);

    const result = await updateSpeakerProfile(formData);

    if (result.error) {
      toast.error(result.error);
      setSaving(false);
      return;
    }

    toast.success("Profile saved successfully.");
    setSaving(false);
  };

  const displayPhotoUrl = photoUrl || undefined;
  const photoFrameStyle = getPhotoFrameImageStyle(photoFrame);
  const initials = getInitials(name || speaker?.name || null, userEmail);

  return (
    <form onSubmit={handleSubmit} className="space-y-8 max-w-2xl">
      {/* Photo upload section */}
      <Card id="profile-photo-section" className="border-[#e2e8f0]">
        <CardHeader>
          <CardTitle className="text-[#1B365D]">Profile Photo</CardTitle>
          <CardDescription>
            Your photo appears on your Fanflet pages. JPG, PNG, or WebP under 5MB.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col sm:flex-row items-start gap-6">
          <Avatar className="w-20 h-20 border-2 border-[#e2e8f0] shrink-0">
            <AvatarImage src={displayPhotoUrl} alt="Profile" className="object-cover" style={photoFrameStyle} />
            <AvatarFallback className="bg-[#3BA5D9]/20 text-[#1B365D] text-xl font-semibold">
              {initials}
            </AvatarFallback>
          </Avatar>
          <div className="flex flex-col gap-2">
            <input
              ref={fileInputRef}
              type="file"
              accept="image/jpeg,image/png,image/webp,image/gif"
              className="hidden"
              onChange={handlePhotoSelect}
              disabled={cropModalOpen}
            />
            <Button
              id="upload-photo-button"
              type="button"
              variant="outline"
              onClick={() => fileInputRef.current?.click()}
              disabled={cropModalOpen}
              className="border-[#3BA5D9] text-[#1B365D] hover:bg-[#3BA5D9]/10"
            >
              <Upload className="w-4 h-4" />
              Upload Photo
            </Button>
            {displayPhotoUrl && (
              <>
                <Button
                  type="button"
                  variant="outline"
                  onClick={handleAdjustPhoto}
                  disabled={cropModalOpen}
                  className="border-[#e2e8f0] text-[#1B365D] hover:bg-slate-100"
                >
                  Adjust photo
                </Button>
                <Button
                  type="button"
                  variant="ghost"
                  onClick={handleRemovePhoto}
                  disabled={cropModalOpen}
                  className="text-destructive hover:text-destructive hover:bg-destructive/10"
                >
                  <Trash2 className="w-4 h-4" />
                  Remove photo
                </Button>
              </>
            )}
            <PhotoCropModal
              open={cropModalOpen}
              onOpenChange={handleCropOpenChange}
              file={cropModalFile}
              existingPhotoUrl={cropModalExistingUrl}
              initialFrame={cropModalFile ? null : photoFrame}
              authUserId={authUserId}
              onSaved={handleCropSaved}
            />
          </div>
        </CardContent>
      </Card>

      {/* Profile fields */}
      <Card id="profile-info-section" className="border-[#e2e8f0]">
        <CardHeader>
          <CardTitle className="text-[#1B365D]">Profile Information</CardTitle>
          <CardDescription>
            Basic details that appear on your public Fanflet pages.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="name" className="text-[#1B365D]">
              Name <span className="text-destructive">*</span>
            </Label>
            <Input
              id="name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="Your full name"
              required
              className="border-[#e2e8f0] focus:border-[#3BA5D9] focus:ring-[#3BA5D9]/30"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="bio" className="text-[#1B365D]">
              Bio
            </Label>
            <Textarea
              id="bio"
              value={bio}
              onChange={(e) => setBio(e.target.value.slice(0, 500))}
              placeholder="A short bio about you..."
              maxLength={500}
              rows={4}
              className="border-[#e2e8f0] focus:border-[#3BA5D9] focus:ring-[#3BA5D9]/30 resize-none"
            />
            <p className="text-xs text-muted-foreground text-right">
              {bio.length}/500
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="slug" className="text-[#1B365D]">
              Public profile link <span className="text-destructive">*</span>
            </Label>
            <div className="flex items-center gap-2">
              <span className="text-sm text-muted-foreground whitespace-nowrap shrink-0">
                fanflet.com/
              </span>
              <div className="flex-1 flex items-center gap-2">
                <Input
                  id="slug"
                  value={slug}
                  onChange={(e) =>
                    setSlug(
                      e.target.value
                        .toLowerCase()
                        .replace(/\s+/g, "-")
                        .replace(/[^a-z0-9-]/g, "")
                    )
                  }
                  placeholder="your-name"
                  required
                  className="border-[#e2e8f0] focus:border-[#3BA5D9] focus:ring-[#3BA5D9]/30 font-mono"
                />
                {slugChecking && (
                  <Loader2 className="w-4 h-4 animate-spin text-muted-foreground shrink-0" />
                )}
                {!slugChecking && slug.trim() && slugAvailable === true && (
                  <Check className="w-5 h-5 text-emerald-600 shrink-0" />
                )}
                {!slugChecking && slug.trim() && slugAvailable === false && (
                  <X className="w-5 h-5 text-destructive shrink-0" />
                )}
              </div>
            </div>
            <p className="text-xs text-muted-foreground">
              Lowercase letters, numbers, and hyphens only. Your profile will be at
              fanflet.com/{slug || "your-slug"}.
            </p>
          </div>
        </CardContent>
      </Card>

      <Card id="default-theme-section" className="border-[#e2e8f0]">
        <CardHeader>
          <CardTitle className="text-[#1B365D]">Default Fanflet Theme</CardTitle>
          <CardDescription>
            Pick the color theme used by default for new Fanflets. You can still override this per Fanflet.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <ThemePicker
            selectedThemeId={defaultThemePreset}
            onChange={setDefaultThemePreset}
            allowMultipleThemes={allowMultipleThemes}
            upgradeHref="/dashboard/settings#subscription"
          />
        </CardContent>
      </Card>

      {/* Social links */}
      <Card className="border-[#e2e8f0]">
        <CardHeader>
          <CardTitle className="text-[#1B365D]">Social Links</CardTitle>
          <CardDescription>
            Optional links to display on your Fanflet pages.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="linkedin" className="text-[#1B365D]">
              LinkedIn
            </Label>
            <Input
              id="linkedin"
              type="url"
              value={linkedin}
              onChange={(e) => setLinkedin(e.target.value)}
              placeholder="https://linkedin.com/in/yourprofile"
              className="border-[#e2e8f0] focus:border-[#3BA5D9] focus:ring-[#3BA5D9]/30"
            />
          </div>
          <Separator />
          <div className="space-y-2">
            <Label htmlFor="twitter" className="text-[#1B365D]">
              X (Twitter)
            </Label>
            <Input
              id="twitter"
              type="url"
              value={twitter}
              onChange={(e) => setTwitter(e.target.value)}
              placeholder="https://x.com/yourhandle"
              className="border-[#e2e8f0] focus:border-[#3BA5D9] focus:ring-[#3BA5D9]/30"
            />
          </div>
          <Separator />
          <div className="space-y-2">
            <Label htmlFor="website" className="text-[#1B365D]">
              Website
            </Label>
            <Input
              id="website"
              type="url"
              value={website}
              onChange={(e) => setWebsite(e.target.value)}
              placeholder="https://yoursite.com"
              className="border-[#e2e8f0] focus:border-[#3BA5D9] focus:ring-[#3BA5D9]/30"
            />
          </div>
        </CardContent>
      </Card>

      <Button
        type="submit"
        disabled={saving || slugAvailable === false}
        className="bg-[#1B365D] hover:bg-[#1B365D]/90 text-white px-8"
      >
        {saving ? (
          <>
            <Loader2 className="w-4 h-4 animate-spin" />
            Saving...
          </>
        ) : (
          "Save Profile"
        )}
      </Button>
    </form>
  );
}
